global:
 scrape_interval: 5s 

scrape_configs:
 - job_name: "prometheus"
   static_configs:
     - targets: 
       - "prometheus:9090"

 - job_name: "vaued-nodejs-app"
   static_configs:
     - targets:
       - "vaued-nodejs-app:8080"

 - job_name: 'mysql-exporter'
   static_configs:
     - targets:
       - 'mysql-exporter:9104'

 - job_name: 'node'
   static_configs:
     - targets:
       - 'node-exporter:9100'
