{
 "title": "VAUED Dashboard - Latest",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": "mysql-exporter:9104" }
  ]
 },
 "panels": [
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle'}[5m])))) * 100) / count(count(node_cpu_seconds_total) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / \r\nnode_memory_MemTotal_bytes)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\r\n((node_filesystem_avail_bytes{fstype!=\"rootfs\", mountpoint=\"/mnt\"} * 100) / \r\nnode_filesystem_size_bytes{fstype!=\"rootfs\", mountpoint=\"/mnt\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_time_seconds -\r\nnode_boot_time_seconds) / 60 / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!=\"rootfs\", mountpoint=\"/mnt\"} /1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (instance)(node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NodeJS App",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate (R): Number of requests per minute",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count[1m]))",
     "legendFormat": "Requests per minute"
    }
   ]
  },
  {
   "title": "Errors (E): The number of failed requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{code=~\"5.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Duration (D): The amount of time to process a request",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket[10m])) by (le, route))",
     "legendFormat": "p90 {{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[10m])) by (le, route))",
     "legendFormat": "Median {{route}}"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "Average {{route}}"
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "host",
   "targets": [
    {}
   ]
  },
  {
   "title": "QPS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_queries[5m])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Instances Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": " " }
   ]
  },
  {
   "title": "MySQL Up Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime/60/60"
    }
   ]
  },
  {
   "title": "Inno DB buffer pool size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_buffer_pool_size/1024/1024",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "MySQL Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(mysql_global_status_bytes_received{instance=\"mysql-exporter:9104\"}[1h])",
     "legendFormat": "Received"
    },
    {
     "expr": "increase(mysql_global_status_bytes_sent{instance=\"mysql-exporter:9104\"}[1h])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "MySQL Table Locks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_table_locks_immediate[5m])",
     "legendFormat": "immediate"
    },
    {
     "expr": "irate(mysql_global_status_table_locks_waited\r[5m])",
     "legendFormat": "waited"
    }
   ]
  },
  {
   "title": "MySQL Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[1m]))"
    }
   ]
  },
  {
   "title": "MySQL Memory Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_innodb_page_size{instance=\"mysql-exporter:9104\"} * on(instance) mysql_global_status_buffer_pool_pages{instance=\"mysql-exporter:9104\",state=\"data\"}",
     "legendFormat": "InnoDB page data"
    },
    {
     "expr": "mysql_global_variables_key_buffer_size{instance=\"mysql-exporter:9104\"\r}",
     "legendFormat": "Key Buffer Size"
    },
    {
     "expr": "mysql_global_variables_innodb_log_buffer_size{instance=\r\"mysql-exporter:9104\"}",
     "legendFormat": "InnoDB Log Buffer Size"
    }
   ]
  },
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Memory Chunks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Series",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Engine Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum(prometheus_engine_query_duration_seconds_sum) by (slice)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}